# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'
  env:
    VUE_APP_TWITCH_PUBLIC_CLIENT_ID: '$(VUE_APP_TWITCH_PUBLIC_CLIENT_ID)'
    VUE_APP_ROOT_API: 'https://openuitwitchbotapi.azurewebsites.net/api'
    VUE_APP_ROOT: 'https://openuitwitchbot.azurewebsites.net'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'web.config'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'dist/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'published'
    publishLocation: 'Container'
